# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FICcourse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FICcourse
  pod 'Cartography', '~> 4.0.0'

  target 'FICcourseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FICcourseUITests' do
    # Pods for testing
  end

end
